# =============================================================================
# loader.conf — systemd-boot loader configuration
# =============================================================================

default  01-archiso-x86_64-nvidia.conf
timeout  5
console-mode max
editor   no
